//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeAQuestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassList
    {
        public int CourseId { get; set; }
        public string StudentId { get; set; }
        public string Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Course Course { get; set; }
    }
}
