//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeAQuestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.ClassLists = new HashSet<ClassList>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int SectionId { get; set; }
        public string CourseDesignator { get; set; }
        public string CourseName { get; set; }
        public string ProfessorId { get; set; }
        public string Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<ClassList> ClassLists { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
