//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeAQuestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int ResponseId { get; set; }
        public int QuestionId { get; set; }
        public string Response1 { get; set; }
        public string Submitter { get; set; }
        public System.DateTime Time { get; set; }
        public string Status { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
