//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeAQuestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int SessionId { get; set; }
        public int CourseId { get; set; }
        public Nullable<bool> AnonOn { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
